" -- Plugins --
" ~/.vim_dotfiles is a symlink to a directory under git control
:set runtimepath+=~/.vim_dotfiles
" Load plugins in ~/.vim/bundle and ~/.vim_dotfiles/bundle
execute pathogen#infect()


" -- Generic config stuff --
:syntax enable
:set hlsearch
:set incsearch
:set scrolloff=7
:set autoindent
:set shiftwidth=4
:set softtabstop=4
:set expandtab
:set colorcolumn=80
:set nu
filetype on
filetype plugin on
:let mapleader = ","
" Webpack workaround
" https://github.com/webpack/webpack/issues/781
:set backupcopy=yes

" -- Color theme --
if has('gui_running')
    :colorscheme solarized
    set background=dark
    let g:solarized_diffmode="high"
else
    :colorscheme darkblue
endif


" --  Lint --
" Display error for non-breaking space or trailing space
au VimEnter,BufWinEnter * syn match ErrorMsg " "
au VimEnter,BufWinEnter * syn match ErrorMsg " $"


" -- Keyboard shortcuts --
" Ctrl+Tab to move between splits
map <C-Tab> <C-W>w
" F10 for paste toggle (toggle paste mode)
:set pastetoggle=<F10>


" -- NERDTree --
" https://github.com/jistr/vim-nerdtree-tabs
let g:nerdtree_tabs_open_on_gui_startup = 0
let g:nerdtree_tabs_autofind = 1
map <F2> :NERDTreeTabsToggle<CR>

" Shortcuts to move between tabs with Ctrl+Shift+Left/Right
" https://stackoverflow.com/a/48112110
function TabLeft()
   if tabpagenr() == 1
      execute "tabm"
   else
      execute "tabm -1"
   endif
endfunction

function TabRight()
   if tabpagenr() == tabpagenr('$')
      execute "tabm" 0
   else
      execute "tabm +1"
   endif
endfunction

map <silent><C-S-Right> :execute TabRight()<CR>
map <silent><C-S-Left> :execute TabLeft()<CR>

" Refresh NERDTree on write
" http://superuser.com/a/1142059/464608
autocmd BufWritePost * NERDTreeFocus | execute 'normal R' | wincmd p


" -- NERDCommenter --
" https://github.com/scrooloose/nerdcommenter
" Align line-wise comment delimiters flush left 
" instead of following code indentation
let g:NERDDefaultAlign = 'start'
" Allow commenting and inverting empty lines (useful when commenting a region)
let g:NERDCommentEmptyLines = 1
map <silent><C-C> <Plug>NERDCommenterComment
map <silent><C-D> <Plug>NERDCommenterUncomment


" -- Pytest --
nmap <silent><Leader>f <Esc>:Pytest file<CR>
nmap <silent><Leader>c <Esc>:Pytest class<CR>
nmap <silent><Leader>m <Esc>:Pytest method<CR>


" -- Local settings --
if filereadable(glob('~/.vimrc_local'))
    source ~/.vimrc_local
endif
